// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClf5z-pG0rEcQTdsA_q9W66toI4Y6HR9s',
    appId: '1:753120326228:web:29e5d2b9c47edca95573c1',
    messagingSenderId: '753120326228',
    projectId: 'firestore-5e8b6',
    authDomain: 'firestore-5e8b6.firebaseapp.com',
    storageBucket: 'firestore-5e8b6.appspot.com',
    measurementId: 'G-86SECWFRGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhZpEnJkOxHbpWYdaQLT0RWAtUC6j1nwg',
    appId: '1:753120326228:android:595968fb4a3b605f5573c1',
    messagingSenderId: '753120326228',
    projectId: 'firestore-5e8b6',
    storageBucket: 'firestore-5e8b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrcn7UaqCr--jrm-oxEH7UBot-KQ_ByMo',
    appId: '1:753120326228:ios:5e1bc24e3562b68b5573c1',
    messagingSenderId: '753120326228',
    projectId: 'firestore-5e8b6',
    storageBucket: 'firestore-5e8b6.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrcn7UaqCr--jrm-oxEH7UBot-KQ_ByMo',
    appId: '1:753120326228:ios:1cd92bc6b642b2885573c1',
    messagingSenderId: '753120326228',
    projectId: 'firestore-5e8b6',
    storageBucket: 'firestore-5e8b6.appspot.com',
    iosBundleId: 'com.example.firestore.RunnerTests',
  );
}
